#!/usr/bin/env python3
"""Copy the project's music into the game project.

This used to also copy thirteen sprites out of GDQuest's starter pack. Those
sprites were CC BY-NC-SA 4.0 - free to share and specifically not sellable -
and were the only thing standing between Slimer and a paid release, since the
pack's code is MIT and every other sprite was already generated by gen_art.py.

They have been replaced with originals authored in tools/gen_art.py, which now
produces the entire sprite set. Nothing here reads the pack any more, and the
pack itself is no longer part of the project.
"""
from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent      # game/
MUSIC_SRC = ROOT.parent                            # Desktop/Slimer
MUSIC = ROOT / "assets" / "music"


def main() -> None:
    MUSIC.mkdir(parents=True, exist_ok=True)
    print("music:")
    for mp3 in sorted(MUSIC_SRC.glob("*.mp3")):
        dest = mp3.name.lower().replace(" ", "_")
        shutil.copy2(mp3, MUSIC / dest)
        print(f"  {dest}")


if __name__ == "__main__":
    main()
