#!/usr/bin/env python3
"""Assemble the website's static assets from the game project.

Deterministic and safe to re-run: everything under site/assets/ and
site/play/engine/ is generated by this script and nothing else. The game
project, the original GDQuest pack and the root .mp3 files are read-only
here - see HANDOVER.md section 1.

    python3 site/tools/build_site.py

Outputs
    assets/atlas.png + atlas.json   one packed sprite sheet, so each WebGL
                                    scene draws in a single call
    assets/shots/*.webp             the 16 visual-pass screenshots, full + thumb
    assets/og.webp, favicon*.png    social card and icons
    assets/music/*.mp3              the four tracks (click-to-play on the page)
    play/engine/*                   verbatim copy of the Godot web export
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

from PIL import Image

SITE = Path(__file__).resolve().parent.parent
ROOT = SITE.parent
GAME = ROOT / "game"
SPRITES = GAME / "assets" / "sprites"
GEN = SPRITES / "gen"
SHOTS_SRC = Path.home() / "Library" / "Application Support" / "Godot" / "app_userdata" / "Slimer" / "shots"

ASSETS = SITE / "assets"
ATLAS_MAX = 2048

# The game's default_clear_color, project.godot -> Color(0.16, 0.21, 0.16).
CLEAR = (41, 54, 41)

# Sprites the site actually uses. Names are the atlas keys the JS scenes look
# up, so this list is the contract between this script and js/scenes/*.
#
# Files marked PACK are derived from GDQuest's CC BY-NC-SA 4.0 asset pack. They
# may be shown, but only alongside the attribution block the page carries in
# its footer - see game/LICENSE-ASSETS.md. Everything else is original work
# generated by game/tools/gen_art.py and carries no restriction.
CURATED: list[tuple[str, Path]] = []


def add(key: str, path: Path) -> None:
    CURATED.append((key, path))


# -- actors -------------------------------------------------------------------
add("player_body", SPRITES / "boo_body.png")            # PACK
add("player_face", SPRITES / "boo_face.png")            # PACK
add("pistol", SPRITES / "pistol.png")                   # PACK
add("bullet", SPRITES / "projectile.png")               # PACK
add("muzzle", SPRITES / "muzzle_flash.png")             # PACK
add("impact", SPRITES / "impact_circle.png")            # PACK
add("shadow", SPRITES / "ground_shadow.png")            # PACK
add("slime_face", SPRITES / "slime_face.png")           # PACK
for colour in ("green", "blue", "red", "purple", "yellow", "orange"):
    add(f"enemy_{colour}", GEN / f"enemy_{colour}_body.png")   # PACK (hue-rotated)
    add(f"crown_{colour}", GEN / f"elite_crown_{colour}.png")  # original
add("eyes_angry", GEN / "eyes_angry.png")
add("eyes_boss", GEN / "eyes_boss.png")

# -- bosses (all original) ----------------------------------------------------
for boss in ("bramble", "toad", "wisp", "oak", "sovereign"):
    add(f"boss_{boss}", GEN / f"boss_{boss}_body.png")
    add(f"boss_{boss}_eyes", GEN / f"boss_{boss}_eyes.png")
add("boss_orb", GEN / "boss_orb.png")

# -- forest props -------------------------------------------------------------
add("tree_pine", SPRITES / "pine_tree.png")             # PACK
for name in (
    "tree_round_a", "tree_round_b", "tree_dead", "stump", "log_a", "log_b",
    "bush_a", "bush_b", "bush_c", "fern", "reeds", "grass_a", "grass_b",
    "grass_c", "flower_a", "flower_b", "mushroom", "lilypad", "thorn",
    "rock_a", "rock_b", "rock_c", "pebbles", "campfire", "shop_lantern",
):
    add(name, GEN / f"{name}.png")

# -- ground tiles (drawn as one quad per tile, so no GL_REPEAT needed) --------
for name in ("ground_grass", "ground_path", "ground_clearing", "ground_water"):
    add(name, GEN / f"{name}.png")

# -- pickups, fx, ui ---------------------------------------------------------
for name in (
    "essence", "coin_strip", "spark", "spark_square", "orb", "glow", "ring",
    "shockwave", "leaf_0", "leaf_1", "leaf_2", "crosshair",
):
    add(name, GEN / f"{name}.png")
for name in (
    "ammo", "coin", "dash", "decoy", "essence", "grenade", "heal", "heart",
    "lifesteal", "lightning", "nova", "orbital", "rapidfire", "shield",
    "timeslow",
):
    add(f"icon_{name}", GEN / f"icon_{name}.png")
for colour in ("red", "blue", "purple"):
    add(f"potion_{colour}", GEN / f"potion_{colour}.png")


def pack_atlas() -> dict:
    """Shelf-pack the curated sprites into one RGBA sheet."""
    images: list[tuple[str, Image.Image]] = []
    missing = []
    for key, path in CURATED:
        if not path.exists():
            missing.append(f"{key} -> {path}")
            continue
        images.append((key, Image.open(path).convert("RGBA")))
    if missing:
        raise SystemExit("missing source sprites:\n  " + "\n  ".join(missing))

    # A flat opaque swatch, so the renderer can draw tinted primitives -
    # telegraph markers, health bars, hit flashes - through the same single
    # atlas draw call as the sprites. Sampled from its centre, so the 2px pad
    # never bleeds in.
    images.append(("white", Image.new("RGBA", (8, 8), (255, 255, 255, 255))))

    pad = 2
    # Tallest first: shelf packing wastes far less that way.
    order = sorted(images, key=lambda kv: -kv[1].height)
    frames: dict[str, dict] = {}
    x = y = row_h = 0
    for key, img in order:
        w, h = img.width + pad, img.height + pad
        if x + w > ATLAS_MAX:
            x = 0
            y += row_h
            row_h = 0
        frames[key] = {"x": x, "y": y, "w": img.width, "h": img.height}
        x += w
        row_h = max(row_h, h)
    height = y + row_h
    if height > ATLAS_MAX:
        raise SystemExit(f"atlas overflow: needs {height}px, max {ATLAS_MAX}")

    # Power-of-two height keeps some drivers happy and costs nothing.
    pot = 1
    while pot < height:
        pot *= 2
    sheet = Image.new("RGBA", (ATLAS_MAX, pot), (0, 0, 0, 0))
    for key, img in order:
        f = frames[key]
        sheet.paste(img, (f["x"], f["y"]))

    ASSETS.mkdir(parents=True, exist_ok=True)
    sheet.save(ASSETS / "atlas.png", optimize=True)
    manifest = {"width": sheet.width, "height": sheet.height, "frames": frames}
    (ASSETS / "atlas.json").write_text(json.dumps(manifest, indent=1, sort_keys=True))
    return manifest


# Sprites the HTML references directly, as ordinary <img> tags, rather than
# through the WebGL atlas: the boss cards and the ability icons.
HTML_SPRITES = {
    **{f"boss_{b}": GEN / f"boss_{b}_body.png"
       for b in ("bramble", "toad", "wisp", "oak", "sovereign")},
    **{f"icon_{i}": GEN / f"icon_{i}.png" for i in (
        "dash", "grenade", "shield", "nova", "heal", "decoy", "timeslow",
        "lightning", "rapidfire", "orbital", "lifesteal",
    )},
}


def copy_html_sprites() -> None:
    out = ASSETS / "sprites"
    out.mkdir(parents=True, exist_ok=True)
    for key, src in HTML_SPRITES.items():
        if not src.exists():
            raise SystemExit(f"missing sprite for the page: {key} -> {src}")
        shutil.copy2(src, out / f"{key}.png")


def convert_shots() -> list[str]:
    """The 16 visual-pass screenshots, PNG -> WebP at two sizes."""
    out = ASSETS / "shots"
    out.mkdir(parents=True, exist_ok=True)
    if not SHOTS_SRC.is_dir():
        raise SystemExit(
            f"no screenshots at {SHOTS_SRC}\n"
            "regenerate them with:  $G --path game --resolution 1600x900 -- visual"
        )
    names = []
    for src in sorted(SHOTS_SRC.glob("*.png")):
        img = Image.open(src).convert("RGB")
        stem = src.stem
        img.save(out / f"{stem}.webp", "WEBP", quality=82, method=6)
        img.resize((800, 450), Image.LANCZOS).save(
            out / f"{stem}_thumb.webp", "WEBP", quality=78, method=6
        )
        names.append(stem)
    return names


def make_icons() -> None:
    icon = Image.open(GEN / "app_icon.png").convert("RGBA")
    for size in (64, 192, 512):
        name = "favicon.png" if size == 64 else f"icon-{size}.png"
        icon.resize((size, size), Image.LANCZOS).save(ASSETS / name, optimize=True)

    # Social card: the Ancient Oak shot is the most legible frame in the set and
    # is almost entirely original art.
    hero = Image.open(SHOTS_SRC / "12_major_boss.png").convert("RGB")
    card = Image.new("RGB", (1200, 630), CLEAR)
    scaled = hero.resize((1200, 675), Image.LANCZOS).crop((0, 22, 1200, 652))
    card.paste(scaled, (0, 0))
    card.save(ASSETS / "og.webp", "WEBP", quality=85, method=6)


def copy_music() -> None:
    out = ASSETS / "music"
    out.mkdir(parents=True, exist_ok=True)
    for src in sorted((GAME / "assets" / "music").glob("*.mp3")):
        shutil.copy2(src, out / src.name)


def copy_web_export() -> None:
    """Verbatim copy of build/web. Renaming anything here breaks index.js."""
    src = ROOT / "build" / "web"
    dst = SITE / "play" / "engine"
    if not (src / "index.wasm").exists():
        raise SystemExit(f"no web export at {src} - run game/tools/build.sh first")
    if dst.exists():
        shutil.rmtree(dst)
    dst.mkdir(parents=True)
    for f in sorted(src.iterdir()):
        if f.name == ".DS_Store" or f.is_dir():
            continue
        shutil.copy2(f, dst / f.name)


def report() -> None:
    def size_of(path: Path) -> int:
        if path.is_file():
            return path.stat().st_size
        return sum(f.stat().st_size for f in path.rglob("*") if f.is_file())

    print("\n  generated:")
    rows = [
        ("assets/atlas.png", ASSETS / "atlas.png"),
        ("assets/shots/", ASSETS / "shots"),
        ("assets/music/", ASSETS / "music"),
        ("assets/ (total)", ASSETS),
        ("play/engine/", SITE / "play" / "engine"),
    ]
    for label, path in rows:
        print(f"    {label:<22} {size_of(path) / 1e6:>8.2f} MB")
    total = size_of(SITE)
    print(f"    {'site/ deploy total':<22} {total / 1e6:>8.2f} MB\n")


def main() -> None:
    manifest = pack_atlas()
    print(f"  atlas   {len(manifest['frames'])} sprites "
          f"-> {manifest['width']}x{manifest['height']}")
    copy_html_sprites()
    print(f"  sprites {len(HTML_SPRITES)} standalone PNGs for the page")
    shots = convert_shots()
    print(f"  shots   {len(shots)} screenshots -> webp (full + thumb)")
    make_icons()
    print("  icons   favicon, icon-192, icon-512, og.webp")
    copy_music()
    print("  music   4 tracks")
    copy_web_export()
    print("  engine  web export copied")
    report()


if __name__ == "__main__":
    main()
